name: Test Pipeline

on: push # Trigger the workflow whenever the code is pushed

jobs:
  trail-job:
    runs-on: ubuntu-latest # Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # step to checkout code

      - name: Run Script
        run: |
          echo "Hi I'm testing environment setup"
      - name: Success Check
        run: exit 0 # Pipeline will succeed


      # Optional: Failure example step
      #- name: Failure Check
      #  if: ${{ always() }} # Executes even if previous fails(optional)
      #  run: exit 1 # Pipeline will fail
