name: Test Pipeline

# Stages:
# 1. Build
# 2. Test
# 3. Lint
# 4. Package
# 5. Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building Stage Running..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: echo "Testing Stage Running..."

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: echo "Linting Stage Running..."

  package:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - run: echo "Packaging Stage Running..."

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying Stage Running..."
      - run: echo "Deployment Successful!"
